// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-wz7nFw6OSNRb0sHL8Utu4a0uFK9C9Ww',
    appId: '1:497678894055:web:b16c237abb910157bd3342',
    messagingSenderId: '497678894055',
    projectId: 'gtv-mail',
    authDomain: 'gtv-mail.firebaseapp.com',
    storageBucket: 'gtv-mail.firebasestorage.app',
    measurementId: 'G-XNJFH538GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDT-95yF9cQCz6XdkGzwNKjcHCCoIe1qw',
    appId: '1:497678894055:android:953d8c43c20a681bbd3342',
    messagingSenderId: '497678894055',
    projectId: 'gtv-mail',
    storageBucket: 'gtv-mail.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaX1G4NljpHKlmZzxcNlG9JS9KcKgWg4c',
    appId: '1:497678894055:ios:a319a8017fe4990cbd3342',
    messagingSenderId: '497678894055',
    projectId: 'gtv-mail',
    storageBucket: 'gtv-mail.firebasestorage.app',
    iosBundleId: 'com.toangtv.gtvMail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaX1G4NljpHKlmZzxcNlG9JS9KcKgWg4c',
    appId: '1:497678894055:ios:a319a8017fe4990cbd3342',
    messagingSenderId: '497678894055',
    projectId: 'gtv-mail',
    storageBucket: 'gtv-mail.firebasestorage.app',
    iosBundleId: 'com.toangtv.gtvMail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-wz7nFw6OSNRb0sHL8Utu4a0uFK9C9Ww',
    appId: '1:497678894055:web:c6a4c4cddfb597dabd3342',
    messagingSenderId: '497678894055',
    projectId: 'gtv-mail',
    authDomain: 'gtv-mail.firebaseapp.com',
    storageBucket: 'gtv-mail.firebasestorage.app',
    measurementId: 'G-3VYNVM08LT',
  );
}
