const appFonts = {
  'Arial': 'Arial',
  'Times New Roman': 'Times New Roman',
  'Courier New': 'Courier New',
  'Verdana': 'Verdana',
  'Georgia': 'Georgia',
  'Tahoma': 'Tahoma',
  'Comic Sans MS': 'Comic Sans MS',
  'Roboto': 'Roboto',
  'Lobster': 'Lobster',
  'Open Sans': 'Open Sans',
  'Montserrat': 'Montserrat',
  'Merriweather': 'Merriweather',
  'Fira Sans': 'Fira Sans',
  'Raleway': 'Raleway',
  'Dancing Script': 'Dancing Script',
  'Clear Sans': 'Clear Sans',
  'Ubuntu': 'Ubuntu',
  'Poppins': 'Poppins',
  'Cabin': 'Cabin',
  'Helvetica': 'Helvetica',
};