on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.3'

      # Install dependencies
      - run: flutter pub get

      # Debug home and cache directory
      - name: Debug home and pub-cache
        run: |
          echo "HOME directory: $HOME"
          echo "Listing directories in $HOME:"
          ls -R $HOME
        env:
          PUB_CACHE: $HOME/.pub-cache

      # Verify notification_permissions location
      - name: Verify notification_permissions path
        run: find $PUB_CACHE -name "notification_permissions*"
        env:
          PUB_CACHE: /Users/runner/hostedtoolcache/flutter/3.24.3-stable/arm64/.pub-cache

      # Add namespace to notification_permissions
      - name: Add namespace to notification_permissions
        run: |
          GRADLE_FILE="$PUB_CACHE/hosted/pub.dartlang.org/notification_permissions-0.6.1/android/build.gradle"
          echo "Checking if Gradle file exists at $GRADLE_FILE"
          if [ -f "$GRADLE_FILE" ]; then
            echo "Adding namespace to $GRADLE_FILE"
            sed -i '/android {/a\    namespace "com.vanethos.notification_permissions"' "$GRADLE_FILE"
          else
            echo "Gradle file not found at $GRADLE_FILE!"
            exit 1
          fi
        env:
          PUB_CACHE: /Users/runner/hostedtoolcache/flutter/3.24.3-stable/arm64/.pub-cache


      # Android release build
      - name: Build Android Release APK
        run: flutter build apk --release --split-per-abi
        continue-on-error: true

      # iOS release build
      - name: Build iOS Release IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
        continue-on-error: true

      # Web build
      - name: Build Web
        run: |
          flutter build web
          cd build/web
          zip -r web.zip .
        continue-on-error: true

      # Push to Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk,
            build/ios/iphoneos/app.ipa,
            build/web/web.zip
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
